#!/usr/bin/env python3
# Called by the Quality workflow on every pull request targeting main.
# Performs two checks:
#   1. Compiles resources.qrc with pyrcc5 to validate its syntax (pyrcc5 must be
#      installed in the runner via pyqt5-dev-tools).
#   2. If resources.qrc was modified in the PR (compared to origin/main), verifies
#      that resources.py was also regenerated by comparing SHA-256 hashes. Fails
#      with an actionable message if they are out of sync.
# Exits with code 1 and prints a GitHub Actions error annotation on any violation.
import hashlib
import subprocess
import sys

CI_OUTPUT = '/tmp/resources_ci.py'


def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        h.update(f.read())
    return h.hexdigest()


# Étape 1 — valider le .qrc en le compilant
result = subprocess.run(
    ['pyrcc5', '-o', CI_OUTPUT, 'resources.qrc'],
    capture_output=True, text=True
)
if result.returncode != 0:
    print(f'::error::resources.qrc: échec pyrcc5 — {result.stderr.strip()}')
    sys.exit(1)
print('resources.qrc valide (pyrcc5 OK)')

# Étape 2 — si resources.qrc a changé dans la PR, vérifier que resources.py est à jour
try:
    changed = subprocess.check_output(
        ['git', 'diff', '--name-only', 'origin/main...HEAD'],
        text=True
    ).splitlines()
except subprocess.CalledProcessError:
    changed = []

if 'resources.qrc' not in changed:
    print('resources.qrc non modifié dans cette PR — vérification de sync ignorée')
    sys.exit(0)

if sha256(CI_OUTPUT) != sha256('resources.py'):
    print(
        '::error::resources.qrc a été modifié mais resources.py n\'a pas été '
        'regénéré. Lancez "make compile" et committez resources.py.'
    )
    sys.exit(1)

print('resources.py synchronisé avec resources.qrc')
