# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FluxCEN
                                 A QGIS plugin
 Centralisation des flux WFS/WMS utilisés au CEN NA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-23
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Romain MONTILLET
        email                : r.montillet@cen-na.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt, QUrl
from qgis.PyQt.QtGui import QFont, QDesktopServices, QStandardItemModel, QStandardItem, QIcon, QPixmap
from qgis.PyQt.QtWidgets import QAbstractItemView, QWidget, QTableWidget, QTableWidgetItem, QVBoxLayout, QAction, QMessageBox, QLabel, QDialog, QPushButton, QListWidget
from qgis.utils import iface

from qgis.core import (
    Qgis, QgsApplication, QgsRasterLayer, QgsVectorLayer,
    QgsProject, QgsDataSourceUri)

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .FluxCEN_dialog import FluxCENDialog

import yaml
import os.path, os
from PyQt5.QtXml import QDomDocument
import csv
import os
import io
import re
import ssl
import urllib
from urllib import request, parse
import socket
import requests


# Vérifier la connexion à internet
try:
    # Vérifier si l'utilisateur est connecté à internet en ouvrant une connexion avec un site web
    host = socket.gethostbyname("www.google.com")
    s = socket.create_connection((host, 80), 2)
    s.close()
except socket.error:
    # Afficher un message si l'utilisateur n'est pas connecté à internet
    QMessageBox.warning(None, 'Avertissement',
                        'Vous n\'êtes actuellement pas connecté à internet. Veuillez vous connecter pour pouvoir utiliser FluxCEN !')



class AuthSelectionDialog(QDialog):
    def __init__(self, auth_configs, parent=None):
        super(AuthSelectionDialog, self).__init__(parent)
        self.selected_auth_id = None
        self.auth_config_dict = {}  # Dictionnaire pour stocker l'association entre nom et ID
        
        self.setWindowTitle("Sélectionner une configuration d'authentification")

        layout = QVBoxLayout()

        # List to display available authentication configurations
        self.list_widget = QListWidget(self)
        for auth_id, auth_config in auth_configs.items():
            auth_name = auth_config.name()  # Obtenir le nom de la configuration
            self.list_widget.addItem(auth_name)
            self.auth_config_dict[auth_name] = auth_id  # Associer le nom à l'ID

        layout.addWidget(self.list_widget)

        # OK button
        ok_button = QPushButton("OK")
        ok_button.clicked.connect(self.accept_selection)
        layout.addWidget(ok_button)

        self.setLayout(layout)

    def accept_selection(self):
        # Get the selected item from the list
        selected_item = self.list_widget.currentItem()
        if selected_item:
            selected_name = selected_item.text()
            # Récupérer l'ID associé au nom sélectionné
            self.selected_auth_id = self.auth_config_dict.get(selected_name)
            self.accept()
        else:
            QMessageBox.warning(self, "Sélection requise", "Veuillez sélectionner une configuration d'authentification.")


class FluxCEN:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'FluxCEN_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&FluxCEN')
        self.dlg = FluxCENDialog()

        self.plugin_path = os.path.dirname(__file__)

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.dlg.tableWidget.setSelectionBehavior(QTableWidget.SelectRows)
        self.dlg.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)

        self.dlg.comboBox.currentIndexChanged.connect(self.initialisation_flux)
        self.dlg.commandLinkButton.clicked.connect(self.selection_flux)
        self.dlg.tableWidget.itemDoubleClicked.connect(self.selection_flux)
        self.dlg.pushButton_2.clicked.connect(self.limite_flux)
        self.dlg.commandLinkButton_2.clicked.connect(self.suppression_flux)
        self.dlg.tableWidget_2.itemDoubleClicked.connect(self.suppression_flux)
        self.dlg.comboBox.addItem("toutes les catégories")
        self.dlg.commandLinkButton_3.clicked.connect(self.option_OSM)
        self.dlg.commandLinkButton_4.clicked.connect(self.option_google_maps)

        self.dlg.commandLinkButton_5.clicked.connect(self.choose_default_authentication)
        self.dlg.commandLinkButton_7.clicked.connect(self.show_welcome_popup)

        # iface.mapCanvas().extentsChanged.connect(self.test5)
        # Load URLs and handle possible errors
        try:
            flux_csv_url, last_version_url, _, _= self.load_urls('config/yaml/links.yaml')
        except Exception as e:
            self.iface.messageBar().pushMessage("Error", f"Failed to load URLs: {e}", level=Qgis.Critical, duration=5)
            return
        
        url_open = urllib.request.urlopen(flux_csv_url)
        colonnes_flux = csv.DictReader(io.TextIOWrapper(url_open, encoding='utf8'), delimiter=';')

        mots_cles = [row["categorie"] for row in colonnes_flux if row["categorie"]]
        categories = list(set(mots_cles))
        categories.sort()

        self.dlg.comboBox.addItems(categories)
        layout = QVBoxLayout()
        self.dlg.lineEdit.textChanged.connect(self.filtre_dynamique)
        layout.addWidget(self.dlg.lineEdit)
        self.dlg.lineEdit.mousePressEvent = self._mousePressEvent

        metadonnees_plugin = open(self.plugin_path + '/metadata.txt')
        infos_metadonnees = metadonnees_plugin.readlines()

        derniere_version = urllib.request.urlopen(last_version_url)
        num_last_version = derniere_version.readlines()[0].decode("utf-8")

        # Connect the itemClicked signal to the open_url function
        self.dlg.tableWidget.itemClicked.connect(self.open_url)

        version_utilisateur = infos_metadonnees[8].splitlines()

        if infos_metadonnees[8].splitlines() == num_last_version.splitlines():
            iface.messageBar().pushMessage("Plugin à jour", "Votre version de FluxCEN %s est à jour !" %version_utilisateur, level=Qgis.Success, duration=5)
        else:
            iface.messageBar().pushMessage("Information :", "Une nouvelle version de FluxCEN est disponible, veuillez mettre à jour le plugin !", level=Qgis.Info, duration=120)

    def _mousePressEvent(self, event):
        self.dlg.lineEdit.setText("")
        self.dlg.lineEdit.mousePressEvent = None

        
    def show_welcome_popup(self):
        """
        Affiche une fenêtre avec une image au démarrage, centre l'image et ajoute un texte en dessous.
        """
        # Créer un QDialog (fenêtre personnalisée) et le stocker dans self
        self.welcome_dialog = QDialog()  # Référence persistante
        self.welcome_dialog.setWindowTitle("Nouvelle version disponible !")

        # Créer un layout
        layout = QVBoxLayout()

        # Ajouter une image
        label_image = QLabel()
        pixmap = QPixmap(self.plugin_path + "/icons/logo_fluxcen.jpg")  

        if not pixmap.isNull():
            pixmap = pixmap.scaled(450, 300, Qt.KeepAspectRatio, Qt.SmoothTransformation)
            label_image.setPixmap(pixmap)
            label_image.setAlignment(Qt.AlignCenter)
        else:
            label_image.setText("Image introuvable")
            label_image.setAlignment(Qt.AlignCenter)

        layout.addWidget(label_image)

        # Créer un QLabel pour afficher le changelog en HTML
        changelog_label = QLabel()
        changelog_label.setWordWrap(True)

        try:
            _, _, _, info_changelog = self.load_urls('config/yaml/links.yaml')
            fp = urllib.request.urlopen(info_changelog)
            mybytes = fp.read()
            html_changelog = mybytes.decode("utf8")
            fp.close()
            changelog_label.setText(html_changelog)
            changelog_label.setFont(QFont("Calibri", weight=QFont.Bold))
        except Exception as e:
            changelog_label.setText(f"Erreur lors du chargement du changelog : {e}")

        layout.addWidget(changelog_label)

        # Ajouter un bouton de fermeture
        button = QPushButton("Fermer")
        button.clicked.connect(self.welcome_dialog.close)
        layout.addWidget(button)
        layout.setAlignment(button, Qt.AlignCenter)

        # Appliquer le layout à la fenêtre
        self.welcome_dialog.setLayout(layout)
        self.welcome_dialog.setMinimumSize(550, 450)

        # Afficher la fenêtre en mode non modal
        self.welcome_dialog.show()



    def is_first_run_of_new_version(self):
        """
        Vérifie si c'est la première fois que cette version du plugin est démarrée en utilisant la version
        du plugin stockée dans 'metadata.txt' et la dernière version disponible en ligne.
        """
        settings = QSettings()

        # Obtenir la version actuelle du plugin depuis le fichier 'metadata.txt'
        metadonnees_plugin = open(self.plugin_path + '/metadata.txt')
        infos_metadonnees = metadonnees_plugin.readlines()
        version_utilisateur = infos_metadonnees[8].strip()  # Version actuelle du plugin 

        # Charger la dernière version depuis l'URL
        try:
            _, last_version_url, _, _ = self.load_urls('config/yaml/links.yaml')
            derniere_version = urllib.request.urlopen(last_version_url)
            num_last_version = derniere_version.readlines()[0].decode("utf-8").strip()  # Récupérer la dernière version disponible
        except Exception as e:
            self.iface.messageBar().pushMessage("Error", f"Failed to load URLs: {e}", level=Qgis.Critical, duration=5)
            return False

        # Obtenir la dernière version utilisée stockée dans les paramètres
        last_version = settings.value("FluxCEN/last_version", "", type=str)

        # Comparer la version actuelle avec la dernière version utilisée
        if last_version != version_utilisateur or version_utilisateur != num_last_version:
            # Si la version a changé, c'est un premier démarrage de cette version
            settings.setValue("FluxCEN/last_version", version_utilisateur)  # Mettre à jour la version stockée
            return True

        return False


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('FluxCEN', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget
        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        """
        Fonction appelée au démarrage du plugin.
        """

        # Vérifier si c'est le premier démarrage de cette version
        if self.is_first_run_of_new_version():
            self.show_welcome_popup()


        icon_path = ':/plugins/FluxCEN/icons/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'FluxCEN'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Appeler la fonction pour informer l'utilisateur s'il a plus d'une configuration d'authentification
        self.check_authentication_configs()

        # Autres configurations si nécessaire...
        self.first_start = True


    def check_authentication_configs(self):
        """Vérifie le nombre de configurations d'authentification disponibles et affiche un message si nécessaire."""

        managerAU = QgsApplication.authManager()
        auth_configs = managerAU.availableAuthMethodConfigs()  # Récupérer toutes les configurations disponibles

        # Vérifier si une authentification par défaut a été définie et l'appliquer
        settings = QSettings()
        default_auth_id = settings.value("FluxCEN/default_auth_id", None)
        
        if default_auth_id:
            self.apply_authentication_if_needed(QgsDataSourceUri())  

        elif len(auth_configs) > 1:
            # Si plusieurs configurations sont disponibles et aucune par défaut n'est définie
            QMessageBox.information(
                self.iface.mainWindow(),
                "Choix de la configuration d'authentification",
                "<center>Vous avez plusieurs configurations d'authentification disponibles.</center><br> Veuillez vous assurer de choisir la bonne configuration pour utiliser la couche MFU dans MapCEN.<br>"
                "Vous pouvez définir votre configuration par défault en cliquant sur l'icone en forme de 🛠️ en bas à droite de la fenêtre du plugin."
            )

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&FluxCEN'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    # Charger les configurations depuis le fichier YAML et récupérer les informations de connexion pour PostGIS
    def load_postgis_config(self, yaml_file):
        config_path = os.path.join(self.plugin_path, yaml_file)
        with open(config_path, 'r') as file:
            config = yaml.safe_load(file)
        
        # Assurer que 'database' est une clé valide dans le fichier YAML
        db_config_list = config.get('database', [])
        
        # Trouver et retourner la configuration pour PostGIS
        for db in db_config_list:
            if db['type'] == 'PostGIS':
                return db
        
        return None
    
    
    def load_urls(self, yaml_file):
        # Charger le fichier YAML contenant plusieurs clés
        config_path = os.path.join(self.plugin_path, yaml_file)
        
        # Lire le fichier YAML
        with open(config_path, 'r') as file:
            config = yaml.safe_load(file)
        
        # Extraire les URL pour chaque clé
        github_urls = config.get('github_urls', {})
        depot_plugins_url = config.get('depot_plugins_url', {})

        # Accéder aux sous-clés spécifiques
        flux_csv_url = github_urls.get('flux_csv')  # Utilisation correcte de la clé 'flux_csv'
        styles_couches = github_urls.get('styles_couches')
        info_changelog = github_urls.get('info_changelog')
        last_version_url = depot_plugins_url.get('last_version')

        return flux_csv_url, last_version_url, styles_couches, info_changelog
    

    def suppression_flux(self):
        self.dlg.tableWidget_2.removeRow(self.dlg.tableWidget_2.currentRow())

    def option_OSM(self):
        tms = 'type=xyz&url=https://tile.openstreetmap.org/{z}/{x}/{y}.png&zmax=19&zmin=0'
        layer = QgsRasterLayer(tms, 'OSM', 'wms')

        if not QgsProject.instance().mapLayersByName("OSM"):
            QgsProject.instance().addMapLayer(layer)
        else:
            QMessageBox.question(iface.mainWindow(), u"Fond OSM déjà chargé !", "Le fond de carte OSM est déjà chargé", QMessageBox.Ok)

        OSM_layer = QgsProject.instance().mapLayersByName("OSM")[0]

        root = QgsProject.instance().layerTreeRoot()

        OSM_layer = root.findLayer(OSM_layer.id())
        myClone = OSM_layer.clone()
        parent = OSM_layer.parent()
        parent.insertChildNode(-1, myClone)
        parent.removeChildNode(OSM_layer)


    def option_google_maps(self):
        tms = 'type=xyz&zmin=0&zmax=20&url=https://mt1.google.com/vt/lyrs%3Ds%26x%3D{x}%26y%3D{y}%26z%3D{z}'
        layer = QgsRasterLayer(tms, 'Google Satelitte', 'wms')

        if not QgsProject.instance().mapLayersByName("Google Satelitte"):
            QgsProject.instance().addMapLayer(layer)
        else:
            QMessageBox.question(iface.mainWindow(), u"Fond Google Sat' déjà chargé !", "Le fond de carte Google Satelitte est déjà chargé", QMessageBox.Ok)

        google_layer = QgsProject.instance().mapLayersByName("Google Satelitte")[0]

        root = QgsProject.instance().layerTreeRoot()

        google_layer = root.findLayer(google_layer.id())
        myClone = google_layer.clone()
        parent = google_layer.parent()
        parent.insertChildNode(-1, myClone)
        parent.removeChildNode(google_layer)


    def open_url(self, item):
        url = item.data(Qt.UserRole)
        if url:
            QDesktopServices.openUrl(QUrl(url))



    def initialisation_flux(self):

        # Unpacking de flux_csv_url et on ignore last_version_url, info_changelog, styles_couches
        flux_csv_url, _, _, _ = self.load_urls('config/yaml/links.yaml')

        def csv_import(url):
            url_open = urllib.request.urlopen(url)
            csvfile = csv.reader(io.TextIOWrapper(url_open, encoding='utf8'), delimiter=';')
            #on ne lit pas la première ligne correspondant aux noms des colonnes avec next()
            next(csvfile)
            return csvfile

        data = []
        data2 = []
        model = QStandardItemModel()


        raw = csv_import(flux_csv_url)


        for row in raw:
            data.append(row)
            data2.append(row)
            data = [k for k in data if self.dlg.comboBox.currentText() in k]
            data.sort()
            data2.sort()
            items = [
                QStandardItem(field)
                for field in row]

            model.appendRow(items)

        if self.dlg.comboBox.currentText() == 'toutes les catégories':

            nb_row = len(data2)
            nb_col = len(data2[0])

            self.dlg.tableWidget.setRowCount(nb_row)
            self.dlg.tableWidget.setColumnCount(nb_col)
            for row in range(nb_row):
                for col in range(nb_col):
                    item = QTableWidgetItem(str(data2[row][col]))
                    # Access the value from the 4th column for the current row (style here)
                    value_from_4th_column = str(data2[row][3])
                    # Set tooltip for each row
                    tooltip = f"Nom technique du flux: {value_from_4th_column}"
                    item.setToolTip(tooltip)

                    # Check if the current column is the "Résumé des métadonnées" column
                    if col == 7:
                        # Set icon for the "Résumé des métadonnées" column
                        icon_path = self.plugin_path + '/icons/info_metadata.png' 
                        icon = QIcon(icon_path)
                        item.setIcon(icon)   
                        # Store the URL in the item's data for later retrieval
                        url_from_6th_column = str(data2[row][7])  
                        item.setData(Qt.UserRole, url_from_6th_column)

                    self.dlg.tableWidget.setItem(row, col, item)
        else:
            nb_row = len(data)
            nb_col = len(data[0])
            self.dlg.tableWidget.setRowCount(nb_row)
            self.dlg.tableWidget.setColumnCount(nb_col)
            for row in range(nb_row):
                for col in range(nb_col):
                    item = QTableWidgetItem(str(data[row][col]))
                    ## Problème ici car décalage d'une ligne :
                    ##  Access the value from the 4th column for the current row (style here)
                    # value_from_4th_column = str(data2[row][3])
                    ##  Set tooltip for each row
                    # tooltip = f"Nom technique du flux: {value_from_4th_column}"
                    # item.setToolTip(tooltip)

                    # Check if the current column is the "Résumé des métadonnées" column
                    if col == 7:
                        # Set icon for the "Résumé des métadonnées" column
                        icon_path = self.plugin_path + '/icons/metadata.png' 
                        icon = QIcon(icon_path)
                        item.setIcon(icon)   
                        # Store the URL in the item's data for later retrieval
                        url_from_6th_column = str(data2[row][7])  
                        item.setData(Qt.UserRole, url_from_6th_column)

                    self.dlg.tableWidget.setItem(row, col, item)

        self.dlg.tableWidget.setHorizontalHeaderLabels(["Service", "Catégorie", "Flux", "Nom technique", "Url d'accès", "Source", "Style", "Infos"])

        self.dlg.tableWidget.setColumnWidth(0, 76)
        self.dlg.tableWidget.setColumnWidth(1, 0)
        self.dlg.tableWidget.setColumnWidth(2, 610)
        self.dlg.tableWidget.setColumnWidth(3, 0)
        self.dlg.tableWidget.setColumnWidth(4, 0)
        self.dlg.tableWidget.setColumnWidth(5, 88)
        self.dlg.tableWidget.setColumnWidth(6, 0)
        self.dlg.tableWidget.setColumnWidth(7, 30)
        self.dlg.tableWidget.setColumnWidth(8, 0)
        self.dlg.tableWidget.setColumnWidth(9, 0)

        self.dlg.tableWidget.selectRow(0)

    def selection_flux(self):
        selected_row = 0
        selected_items = self.dlg.tableWidget.selectedItems()

        new_item_text = selected_items[3].text()

        if not self.item_already_exists(new_item_text):
            self.dlg.tableWidget_2.insertRow(selected_row)

            for column in range(self.dlg.tableWidget.columnCount()):
                cloned_item = selected_items[column].clone()
                self.dlg.tableWidget_2.setHorizontalHeaderLabels(["Service", "Catégorie", "Flux sélectionné", "Nom technique", "Url d'accès", "Source", "Style", "Infos"])
                self.dlg.tableWidget_2.setColumnCount(10)
                self.dlg.tableWidget_2.setItem(selected_row, column, cloned_item)

            self.dlg.tableWidget_2.setColumnWidth(0, 80)
            self.dlg.tableWidget_2.setColumnWidth(1, 0)
            self.dlg.tableWidget_2.setColumnWidth(2, 640)
            self.dlg.tableWidget_2.setColumnWidth(3, 0)
            self.dlg.tableWidget_2.setColumnWidth(4, 0)
            self.dlg.tableWidget_2.setColumnWidth(5, 100)
            self.dlg.tableWidget_2.setColumnWidth(6, 0)
            self.dlg.tableWidget_2.setColumnWidth(7, 0)
            self.dlg.tableWidget_2.setColumnWidth(8, 0)
            self.dlg.tableWidget_2.setColumnWidth(9, 0)

    def item_already_exists(self, new_item_text):

        existing_items = self.dlg.tableWidget_2.findItems(new_item_text, QtCore.Qt.MatchExactly)

        return len(existing_items) > 0


    def limite_flux(self):

        if self.dlg.tableWidget_2.rowCount() > 3:
            self.QMBquestion = QMessageBox.question(iface.mainWindow(), u"Attention !",
                                                    "Le nombre de flux à charger en une seule fois est limité à 3 pour des questions de performances. Souhaitez vous tout de même charger les " + str(
                                                        self.dlg.tableWidget_2.rowCount()) + " flux sélectionnés ? (risque de plantage de QGIS)",
                                                    QMessageBox.Yes | QMessageBox.No)
            if self.QMBquestion == QMessageBox.Yes:
                self.chargement_flux()

            if self.QMBquestion == QMessageBox.No:
                print("Annulation du chargement des couches")

        if self.dlg.tableWidget_2.rowCount() <= 3:
            self.chargement_flux()


    def apply_qml_style(self, wfs_layer, style_url):
        """
        Function to apply QML style to a WFS layer.
        """

        try:
            # Récupération des styles depuis url github
            response = request.urlopen(style_url)
            style_data = response.read()

            #"Décorticage" du style QML en utilisant QDomDocument
            document = QDomDocument()
            if not document.setContent(style_data):
                print("Echec de l'ouverture du style QML.")
                return

            # on applique le style au flux
            if not wfs_layer.importNamedStyle(document):
                print(f"Echec, le style n'a pas pu être appliqué au flux: {wfs_layer.name()}")
            else:
                print(f"Le style a bien été appliqué au flux: {wfs_layer.name()}")

            #Actualisation de la couche pour prendre en compte le nouveau style
            wfs_layer.triggerRepaint()

        except Exception as e:
            print(f"Problème dans l'application du style: {e}")


    def choose_default_authentication(self):
        managerAU = QgsApplication.authManager()
        auth_configs = managerAU.availableAuthMethodConfigs()  # Récupérer toutes les configurations disponibles

        if not auth_configs:
            QMessageBox.warning(self.dlg, "Pas de configurations", "Aucune configuration d'authentification disponible.")
            return

        dialog = AuthSelectionDialog(auth_configs)
        if dialog.exec_() == QDialog.Accepted:
            selected_auth_id = dialog.selected_auth_id
            # Enregistrer la configuration par défaut dans QSettings
            settings = QSettings()
            settings.setValue("FluxCEN/default_auth_id", selected_auth_id)
            QMessageBox.information(self.dlg, "Configuration sauvegardée", "La configuration d'authentification par défaut a été définie.")


    def apply_authentication_if_needed(self, uri):
        """
        Applique une configuration d'authentification si nécessaire.
        Charge automatiquement la configuration par défaut si elle est enregistrée dans QSettings.
        """
        settings = QSettings()
        default_auth_id = settings.value("FluxCEN/default_auth_id", None)

        # Si une configuration par défaut existe, on l'applique automatiquement
        if default_auth_id:
            uri.setAuthConfigId(default_auth_id)
            return True

        # Si aucune configuration par défaut n'est définie, ouvrir la boîte de dialogue
        managerAU = QgsApplication.authManager()
        auth_configs = managerAU.availableAuthMethodConfigs()  # Récupérer toutes les configurations disponibles

        if len(auth_configs) == 1:
            # Si une seule configuration est disponible, on l'applique directement
            auth_id = list(auth_configs.keys())[0]
            uri.setAuthConfigId(auth_id)
            return True
        elif len(auth_configs) > 1:
            # Si plusieurs configurations sont disponibles, on invite l'utilisateur à en choisir une
            dialog = AuthSelectionDialog(auth_configs)
            result = dialog.exec_()
            if result == QDialog.Accepted and dialog.selected_auth_id:
                uri.setAuthConfigId(dialog.selected_auth_id)
                return True
        else:
            QMessageBox.warning(iface.mainWindow(), "Attention", "Aucune configuration d'authentification n'a été trouvée dans votre QGIS. Veuillez ajouter la configuration d'authentification CEN-NA pour charger les flux sécurisés tels que la MFU .")
            



    def avertissement_pas_de_flux(self):
        """
        Affiche un QMessageBox pour indiquer qu'il n'y a pas de flux à charger si tableWidget_2 est vide.
        """
        QMessageBox.information(iface.mainWindow(), "Aucun flux pré-chargé", "Il n'y a aucun flux à charger dans la table de sélection.", QMessageBox.Ok)


    def chargement_flux(self):
        """
        Main function to load layers from tableWidget_2 based on service type (WMS, WFS, PostGIS).
        """
        _, _, styles_couches, _ = self.load_urls('config/yaml/links.yaml')

        if self.dlg.tableWidget_2.rowCount() == 0:
            self.avertissement_pas_de_flux()
            return

        for row in range(self.dlg.tableWidget_2.rowCount()):
            try:
                # Utilisation de la fonction de validation des données
                data = self.parse_table_row(row, styles_couches)
                if not data:
                    continue  # Si des données manquent, passer à la ligne suivante

                service, nom_couche, nom_technique, url, style_url = data

                # Gestion des types de service (WFS, WMS, PostGIS)
                if service.startswith("WMS"):
                    self.handle_wms_layer(row, nom_couche, nom_technique, url, style_url)
                elif service == "WFS":
                    self.handle_wfs_layer(row, nom_couche, nom_technique, url, style_url)
                elif service == "PostGIS":
                    self.handle_postgis_layer(row)

            except Exception as e:
                print(f"Erreur lors du chargement de la ligne: {row}, Erreur: {e}")
                continue  # Passer à la ligne suivante en cas d'erreur


        # Vider le contenu de tableWidget_2
        self.dlg.tableWidget_2.clearContents()  # Efface les cellules existantes
        self.dlg.tableWidget_2.setRowCount(0)   # Réinitialise le nombre de lignes à 0

    def parse_table_row(self, row, styles_couches):
        """
        Extract relevant data from a given row in tableWidget_2.
        """
        try:
            service = self.dlg.tableWidget_2.item(row, 0).text()  # Type of service (WFS, WMS, PostGIS)
            nom_couche = self.dlg.tableWidget_2.item(row, 2).text()  # Layer name
            nom_technique = self.dlg.tableWidget_2.item(row, 3).text()  # Technical layer name
            url = self.dlg.tableWidget_2.item(row, 4).text()  # URL of the service
            nom_style = self.dlg.tableWidget_2.item(row, 6).text()  # Optional QML style

            # Validation des données
            if not service or not nom_couche or not nom_technique or not url:
                print(f"Données manquantes dans la ligne: {row}")
                return None  # Si une donnée importante manque, on retourne None

            # Construction du chemin du style si disponible
            style_url = styles_couches + nom_style + ".qml" if nom_style and len(nom_style.strip()) >= 2 else None

            return service, nom_couche, nom_technique, url, style_url

        except Exception as e:
            print(f"Erreur lors de la récupération des données de la ligne: {row}, Erreur: {e}")
            return None


    def handle_wms_layer(self, row, nom_couche, nom_technique, url, style_url):
        """
        Handle WMS layer loading and apply authentication if necessary.
        """
        try:
            version = re.search('VERSION=(.+?)&REQUEST', url).group(1)
        except:
            version = '1.0.0'

        wms_layer_url = (
            f"url={url}&"
            f"service=WMS&"
            f"version={version}&"
            f"crs=EPSG:2154&"
            f"format=image/png&"
            f"layers={nom_technique}&"
            f"styles"
        )

        uri = QgsDataSourceUri()
        # Toujours appliquer une config d'authentification QGIS si dispo
        managerAU = QgsApplication.authManager()
        auth_configs = managerAU.availableAuthMethodConfigs()
        if auth_configs:
            # Utiliser la première config trouvée
            first_authcfg = list(auth_configs.keys())[0]
            wms_layer_url_auth = wms_layer_url + f"&authcfg={first_authcfg}"
            wms_layer = QgsRasterLayer(wms_layer_url_auth, nom_couche, "wms")
        else:
            # Pas de config d'authentification : charger sans
            wms_layer = QgsRasterLayer(wms_layer_url, nom_couche, "wms")
            QMessageBox.information(
                iface.mainWindow(),
                "Attention",
                "Aucune configuration d'authentification QGIS n'a été trouvée.\n"
                "Si le flux nécessite une authentification, une fenêtre de connexion QGIS va apparaître."
            )

        if wms_layer.isValid():
            QgsProject.instance().addMapLayer(wms_layer)
        else:
            QMessageBox.critical(
                iface.mainWindow(),
                "Erreur",
                f"Impossible de charger la couche '{nom_couche}'."
            )



    def handle_wfs_layer(self, row, nom_couche, nom_technique, url, style_url):
        """
        Handle WFS layer loading and apply authentication if necessary.
        """
        try:
            version = re.search('VERSION=(.+?)&REQUEST', url).group(1)
        except:
            version = '1.0.0'

        uri = QgsDataSourceUri()
        uri.setParam("url", url)
        uri.setParam("version", version)
        uri.setParam("typename", nom_technique)
        uri.setParam("request", "GetFeature")

        # Toujours appliquer une config d'authentification QGIS si dispo
        managerAU = QgsApplication.authManager()
        auth_configs = managerAU.availableAuthMethodConfigs()
        if auth_configs:
            # Utiliser la première config trouvée
            first_authcfg = list(auth_configs.keys())[0]
            uri.setAuthConfigId(first_authcfg)
            wfs_layer = QgsVectorLayer(uri.uri(False), nom_couche, "WFS")
        else:
            # Pas de config d'authentification : charger sans
            wfs_layer = QgsVectorLayer(uri.uri(False), nom_couche, "WFS")
            QMessageBox.information(
                iface.mainWindow(),
                "Attention",
                "Aucune configuration d'authentification QGIS n'a été trouvée.\n"
                "Si le flux nécessite une authentification, une fenêtre de connexion QGIS va apparaître."
            )

        if wfs_layer.isValid():
            QgsProject.instance().addMapLayer(wfs_layer)
            if style_url:
                self.apply_qml_style(wfs_layer, style_url)
        else:
            QMessageBox.critical(
                iface.mainWindow(),
                "Erreur",
                f"Impossible de charger la couche '{nom_couche}'."
            )




    def handle_postgis_layer(self, row):
        """
        Handle PostGIS layer loading and apply authentication if necessary.
        """
        postgis_config = self.load_postgis_config('config/yaml/config_db.yaml')
        if not postgis_config:
            QMessageBox.critical(iface.mainWindow(), "Erreur", "Impossible de charger la configuration PostGIS depuis le fichier YAML.", QMessageBox.Ok)
            return

        db_host = postgis_config['host']
        db_port = str(postgis_config['port'])
        db_name = self.dlg.tableWidget_2.item(row, 8).text()
        schema_name = self.dlg.tableWidget_2.item(row, 9).text()
        table_name = self.dlg.tableWidget_2.item(row, 3).text()

        if not (db_host and db_port and db_name and schema_name and table_name):
            QMessageBox.critical(iface.mainWindow(), "Erreur", "Des informations de connexion sont manquantes pour la base de données PostGIS.", QMessageBox.Ok)
            return

        uri = QgsDataSourceUri()
        uri.setConnection(db_host, db_port, db_name, None, None)

        if not self.apply_authentication_if_needed(uri):
            return  # Skip if authentication fails

        uri.setDataSource(schema_name, table_name, "geom")

        layer = QgsVectorLayer(uri.uri(False), self.dlg.tableWidget_2.item(row, 2).text(), "postgres")
        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
        else:
            QMessageBox.critical(iface.mainWindow(), "Erreur", f"Échec de chargement de la couche PostGIS : {table_name}", QMessageBox.Ok)



    def filtre_dynamique(self, filter_text):

        for i in range(self.dlg.tableWidget.rowCount()):
            for j in range(self.dlg.tableWidget.columnCount()):
                item = self.dlg.tableWidget.item(i, j)
                match = filter_text.lower() not in item.text().lower()
                self.dlg.tableWidget.setRowHidden(i, match)
                if not match:
                    break



flux_cen_instance = FluxCEN(iface)
