name: Quality

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    if: github.event.pull_request.draft == false
    uses: CEN-Nouvelle-Aquitaine/github-actions/.github/workflows/quality-plugin-qgis.yml@v1
    secrets: inherit
